# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import schedule.models.calendars


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='kalendarz',
            field=models.ForeignKey(auto_created=schedule.models.calendars.Calendar, on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar'),
        ),
    ]
