# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Doctor'),
        ),
    ]
