# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20171107_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pytanie',
            name='autor',
        ),
        migrations.AlterField(
            model_name='terms',
            name='czas',
            field=models.TimeField(default=datetime.datetime(2017, 11, 7, 21, 24, 49, 183120, tzinfo=utc)),
        ),
    ]
