# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20171107_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='czas',
        ),
    ]
