# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20171106_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='kalendarz',
        ),
    ]
